In [88]:
import openrouteservice
import numpy as np

In [89]:
API_KEY = 'eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6ImU5MGU2NzQwNGU4MTQxNDdiNjIzNjNkY2Q5NGRlYmI0IiwiaCI6Im11cm11cjY0In0='
client = openrouteservice.Client(key=API_KEY)

In [90]:
coordinates = []
points = {}

In [91]:
with open('rynek_nodes.txt', "r", encoding='UTF-8') as nodes:
    for row in nodes:
        row = row.replace('\n', '')
        row_splitted = (row.split('\t'))
        row_nums = [float(row_splitted[-1]), row_splitted[-2]]
        coordinates.append(row_nums)
        points[int(row_splitted[0])] = row_splitted[1:3] + (row_nums)

In [92]:
points

{0: ['Restauracja Sukiennice', 'R', 19.936889, '50.061422'],
 1: ['Ratuszowa', 'R', 19.936366, '50.061410'],
 2: ['Arkady Cafe & Cocktail Bar', 'B', 19.937332, '50.061892'],
 3: ['Kram s.c.', 'S', 19.937086, '50.061233'],
 4: ['Noworolski', 'R', 19.937311, '50.061412'],
 5: ['Empik', 'S', 19.936059, '50.061126'],
 6: ['Pizza Dominium', 'R', 19.936186, '50.061061'],
 7: ['Sphinx', 'R', 19.935837, '50.061165'],
 8: ['Hotel Imperial', 'H', 19.9356, '50.061250'],
 9: ['Restauracja La Grande Mamma', 'R', 19.935528, '50.061236'],
 10: ['Rękawiczka sklep z pamiątkami', 'S', 19.935244, '50.061037'],
 11: ['Farma Burgerownia Roślinna', 'B', 19.934978, '50.060717'],
 12: ['Timo Ristorante', 'R', 19.935093, '50.060592'],
 13: ['Bordo. Cafe Restaurant Pub Gołębia 3', 'R', 19.935408, '50.060456'],
 14: ['Szybki Lopez', 'R', 19.935627, '50.060348'],
 15: ['Best hot chocolate', 'B', 19.936167, '50.060469'],
 16: ['SPACE Craft Pub', 'R', 19.936226, '50.060485'],
 17: ['Restauracja & Lounge Bar Sempre 

In [93]:
coordinates

[[19.936889, '50.061422'],
 [19.936366, '50.061410'],
 [19.937332, '50.061892'],
 [19.937086, '50.061233'],
 [19.937311, '50.061412'],
 [19.936059, '50.061126'],
 [19.936186, '50.061061'],
 [19.935837, '50.061165'],
 [19.9356, '50.061250'],
 [19.935528, '50.061236'],
 [19.935244, '50.061037'],
 [19.934978, '50.060717'],
 [19.935093, '50.060592'],
 [19.935408, '50.060456'],
 [19.935627, '50.060348'],
 [19.936167, '50.060469'],
 [19.936226, '50.060485'],
 [19.936243, '50.060542'],
 [19.936364, '50.060449'],
 [19.936409, '50.060455'],
 [19.936384, '50.060514'],
 [19.937092, '50.060775'],
 [19.937134, '50.060734'],
 [19.937226, '50.060636'],
 [19.937319, '50.060540'],
 [19.937389, '50.060456'],
 [19.937432, '50.060405'],
 [19.937471, '50.060349'],
 [19.937596, '50.060081'],
 [19.937619, '50.059978'],
 [19.937602, '50.059799'],
 [19.937668, '50.059769'],
 [19.937676, '50.059686'],
 [19.937687, '50.059672'],
 [19.937694, '50.059579'],
 [19.937714, '50.059464'],
 [19.937777, '50.059202'],
 [1

In [ ]:
import openrouteservice
import numpy as np
import time


client = openrouteservice.Client(key=API_KEY)

def get_batched_distance_matrix(coords, chunk_size=50):
    n = len(coords)
    
    full_matrix = np.zeros((n, n))
    
    print(f"Total points: {n}. Total routes to calculate: {n * n}")
    print("Fetching batches. This may take a minute...")

   
    for i in range(0, n, chunk_size):
        for j in range(0, n, chunk_size):

            row_chunk = coords[i:i + chunk_size]
            col_chunk = coords[j:j + chunk_size]
            
         
            locations = row_chunk + col_chunk
            

            sources = list(range(len(row_chunk)))
            destinations = list(range(len(row_chunk), len(row_chunk) + len(col_chunk)))
            
            try:

                response = client.distance_matrix(
                    locations=locations,
                    sources=sources,
                    destinations=destinations,
                    profile='cycling-regular',
                    metrics=['distance'],
                    units='km'
                )
                

                sub_matrix = np.array(response['distances'])
                full_matrix[i:i + chunk_size, j:j + chunk_size] = sub_matrix
                
                print(f"Successfully fetched block [{i}:{i+chunk_size}, {j}:{j+chunk_size}]")
                
               
                time.sleep(1.5)
                
            except Exception as e:
                print(f"Error fetching block [{i}:{i+chunk_size}, {j}:{j+chunk_size}]: {e}")

                return full_matrix
                
    return full_matrix
final_matrix = get_batched_distance_matrix(coordinates)

print("\nFinal Complete Matrix:")
print(np.round(final_matrix, 2))

Total points: 736. Total routes to calculate: 541696
Fetching batches. This may take a minute...
Successfully fetched block [0:50, 0:50]
Successfully fetched block [0:50, 50:100]
Successfully fetched block [0:50, 100:150]
Successfully fetched block [0:50, 150:200]
Successfully fetched block [0:50, 200:250]
Successfully fetched block [0:50, 250:300]
Successfully fetched block [0:50, 300:350]
Successfully fetched block [0:50, 350:400]
Successfully fetched block [0:50, 400:450]
Successfully fetched block [0:50, 450:500]
Successfully fetched block [0:50, 500:550]
Successfully fetched block [0:50, 550:600]
Successfully fetched block [0:50, 600:650]
Successfully fetched block [0:50, 650:700]
Successfully fetched block [0:50, 700:750]
Successfully fetched block [50:100, 0:50]
Successfully fetched block [50:100, 50:100]
Successfully fetched block [50:100, 100:150]
Successfully fetched block [50:100, 150:200]
Successfully fetched block [50:100, 200:250]
Successfully fetched block [50:100, 250:3

In [95]:
final_matrix

array([[0.  , 0.13, 0.08, ..., 0.47, 0.93, 0.32],
       [0.13, 0.  , 0.1 , ..., 0.33, 0.88, 0.35],
       [0.08, 0.1 , 0.  , ..., 0.43, 0.99, 0.41],
       ...,
       [0.42, 0.33, 0.43, ..., 0.  , 0.85, 0.49],
       [0.92, 0.88, 0.99, ..., 0.85, 0.  , 0.77],
       [0.32, 0.35, 0.41, ..., 0.48, 0.78, 0.  ]])

In [96]:
A = final_matrix

In [97]:
A_T = A.T

In [98]:
A_sym = 0.5 * (A + A_T)

In [105]:
A_sym*1000

array([[  0., 130.,  80., ..., 445., 925., 320.],
       [130.,   0., 100., ..., 330., 880., 350.],
       [ 80., 100.,   0., ..., 430., 990., 410.],
       ...,
       [445., 330., 430., ...,   0., 850., 485.],
       [925., 880., 990., ..., 850.,   0., 775.],
       [320., 350., 410., ..., 485., 775.,   0.]])

In [106]:
np.savetxt('symetric_distance_matrix.txt', A_sym*1000, fmt='%.2f')

In [107]:
np.savetxt('original_distance_matrix.txt', final_matrix*1000,  fmt='%.2f')

In [2]:
import numpy as np

In [3]:
yy = np.loadtxt("symetric_distance_matrix.txt", delimiter=' ')

In [4]:
yy[yy == 0] = 2
np.fill_diagonal(yy, 0)

In [5]:
np.savetxt("distance_matrix.csv", yy, delimiter=",")

In [31]:
x = np.arange(0, 737, 80)

In [33]:
x[-1] = 736

In [34]:
x

array([  0,  80, 160, 240, 320, 400, 480, 560, 640, 736])

In [47]:
yy.shape

(736, 736)

In [51]:
yy[0]

array([  0., 130.,  80.,  20.,  30., 150., 150., 150., 165., 185., 210.,
       250., 280., 280., 280., 130., 130., 120., 130., 130., 120., 195.,
       195., 195., 195., 215., 220., 225., 260., 270., 300., 295., 300.,
       300., 320., 325., 335., 360., 335., 290., 280., 220., 210., 190.,
       140., 130., 280., 270., 275., 285., 295., 305., 305., 280., 275.,
       290., 280., 285., 280., 160., 170., 200., 190., 200., 275., 285.,
       320., 325., 395., 245., 245., 215., 195., 185., 250., 320., 235.,
       330., 330., 330., 290., 330., 330., 260., 240., 240., 200., 180.,
       180., 180., 175., 165., 330., 280., 290., 300., 310., 310., 340.,
       340., 360., 370., 355., 330., 290., 300., 310., 320., 350., 330.,
       340., 350., 360., 340., 370., 360., 370., 360., 360., 370., 380.,
       390., 450., 435., 500., 485., 410., 415., 395., 385., 385., 385.,
       395., 340., 330., 260., 250., 250., 230., 220., 210., 180., 180.,
       210., 215., 210., 215., 220., 230., 270., 33